import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layouts/Navbar/Nav";
const vazirmatn = Vazirmatn({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatn.variable} antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
